### ISSUE TITLE
Failed to parse golang plugin config while running in Github Actions

### ISSUE THREAD

**Issue by Makonike** [mosn/envoy-go-ldap-auth#4]
Currently, I am working on adding actions e2e tests for [envoy-go-ldap-auth](https://github.com/Makonike/envoy-go-ldap-auth). I am using the official image for compilation and execution. While the tests pass successfully in my local environment, I encounter parsing errors when running them in GitHub Actions.

How should I go about troubleshooting the issue?

---

environment :

local : mac m1 pro

github actions: ubuntu:latest

Since both the compilation and execution are using the official image, it is unlikely that the environment is the issue.

---

Following files you can find in [here](https://github.com/Makonike/envoy-go-ldap-auth/tree/test-ci).

config.go
```go
package main

import (
	xds "github.com/cncf/xds/go/xds/type/v3"
	"github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/api"
	"github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http"
	"google.golang.org/protobuf/types/known/anypb"
)

func init() {
	http.RegisterHttpFilterConfigParser(&parser{})
	http.RegisterHttpFilterConfigFactory("envoy-go-ldap-auth", configFactory)
}

type config struct {
	host      string
	port      uint64
	baseDN    string
	attribute string
	bindDN    string
	password  string
	filter    string
	timeout   int32
}

type parser struct {
}

func (p *parser) Parse(any *anypb.Any) (interface{}, error) {
	configStruct := &xds.TypedStruct{}
	if err := any.UnmarshalTo(configStruct); err != nil {
		return nil, err
	}

	v := configStruct.Value
	conf := &config{}
	m := v.AsMap()
	if host, ok := m["host"].(string); ok {
		conf.host = host
	}
	if port, ok := m["port"].(float64); ok {
		conf.port = uint64(port)
	}
	if baseDN, ok := m["base_dn"].(string); ok {
		conf.baseDN = baseDN
	}
	if attribute, ok := m["attribute"].(string); ok {
		conf.attribute = attribute
	}
	if bindDN, ok := m["bind_dn"].(string); ok {
		conf.bindDN = bindDN
	}
	if password, ok := m["bind_password"].(string); ok {
		conf.password = password
	}
	if cFilter, ok := m["filter"].(string); ok {
		conf.filter = cFilter
	}

	if timeout, ok := m["timeout"].(float64); ok {
		conf.timeout = int32(timeout)
	}
	if conf.timeout == 0 {
		conf.timeout = 60
	}
	return conf, nil
}

func (p *parser) Merge(parent interface{}, child interface{}) interface{} {
	panic("TODO")
}

func configFactory(c interface{}) api.StreamFilterFactory {
	conf, ok := c.(*config)
	if !ok {
		panic("unexpected config type, should not happen")
	}
	return func(callbacks api.FilterCallbackHandler) api.StreamFilter {
		return &filter{
			callbacks: callbacks,
			config:    conf,
		}
	}
}
```

Makefile:
```makefile

.PHONY: build test-bind-mode

build:
	docker run --rm -v $(PWD):/go/src/go-filter -w /go/src/go-filter \
		-e GOPROXY=https://goproxy.cn \
		golang:1.19 \
		go build -v -o libgolang.so -buildmode=c-shared -buildvcs=false .

test-bind-mode:
	docker rm -f envoy-ldap-test
	docker run --rm -v $(PWD)/example/envoy.yaml:/etc/envoy/envoy.yaml \
		-v $(PWD)/libgolang.so:/etc/envoy/libgolang.so \
		-e GODEBUG=cgocheck=0 \
		-p 10000:10000 \
		--name envoy-ldap-test \
		envoyproxy/envoy:contrib-dev \
		envoy -c /etc/envoy/envoy.yaml &
	sleep 5
	go test test/e2e_bind_test.go

	docker rm -f envoy-ldap-test
```

envoy.yaml
```yaml
static_resources:

  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.golang
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
                      library_id: example
                      library_path: /etc/envoy/libgolang.so
                      plugin_name: envoy-go-ldap-auth
                      plugin_config:
                        "@type": type.googleapis.com/xds.type.v3.TypedStruct
                        value:
                          # required
                          host: localhost
                          port: 3893
                          base_dn: dc=glauth,dc=com
                          attribute: cn
                          # optional
                          # be used in search mode
                          bind_dn: # cn=admin,dc=example,dc=com
                          bind_password: # mypassword
                          # if the filter is set, the filter application will run in search mode.
                          filter: # (&(objectClass=inetOrgPerson)(gidNumber=500)(uid=%s))
                          timeout: 60 # unit is second.

                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            host_rewrite_literal: mosn.io
                            cluster: service_mosn_io

  clusters:
    - name: service_mosn_io
      type: LOGICAL_DNS
      # Comment out the following line to test on v6 networks
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: service_mosn_io
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: mosn.io
                      port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: mosn.io
```

workflow actions yaml
```yaml
name: build ci

on:
  push:
    branches: [ "test-ci" ]
  pull_request:
    branches: [ "test-ci" ]

jobs:
  test-bind:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: prepare glauth
      run: |
        curl -L -o glauth https://github.com/glauth/glauth/releases/download/v2.2.0-RC1/glauth-linux-amd64
        chmod +x glauth

    - name: build
      run: make build

    - name: run glauth
      run: |
        curl -L -o sample.cfg https://raw.githubusercontent.com/glauth/glauth/master/v2/sample-simple.cfg
        ./glauth -c sample.cfg &
        sleep 5

    - name: test-bind-mode
      run: make test-bind-mode
```

e2e_bind_test.go
```go
package test

import (
	"net/http"
	"testing"
)

func TestE2EBind(t *testing.T) {
	req, err := http.NewRequest(http.MethodGet, "http://localhost:10000/", nil)

	resp1, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp1.Body.Close()
	if resp1.StatusCode != http.StatusUnauthorized {
		t.Fatalf("unexpected status code: %v", resp1.StatusCode)
	}

	req.SetBasicAuth("unknown", "dogood")
	resp2, err := http.DefaultClient.Do(req)
	defer resp2.Body.Close()
	if resp2.StatusCode != http.StatusUnauthorized {
		t.Fatalf("unexpected status code: %v", resp2.StatusCode)
	}

	req.SetBasicAuth("hackers", "unknown")
	resp3, err := http.DefaultClient.Do(req)
	defer resp3.Body.Close()
	if resp3.StatusCode != http.StatusUnauthorized {
		t.Fatalf("unexpected status code: %v", resp3.StatusCode)
	}

	req.SetBasicAuth("hackers", "dogood")
	resp4, err := http.DefaultClient.Do(req)
	defer resp4.Body.Close()
	if resp4.StatusCode != http.StatusOK {
		t.Fatalf("unexpected status code: %v", resp4.StatusCode)
	}

	t.Log("E2E test passed")

}
```

locally test result
```bash
go test test/e2e_bind_test.go
[2023-06-01T03:05:38.249Z] "GET / HTTP/1.1" 401 - 0 16 21 - "-" "Go-http-client/1.1" "9c5ad002-c055-4d81-8b43-8c36401ccba4" "localhost:10000" "-"
ok  	command-line-arguments	1.122s
docker rm -f envoy-ldap-test
envoy-ldap-test
```

but panic in github actions, details you can find in [actions result](https://github.com/Makonike/envoy-go-ldap-auth/actions/runs/5136806180/jobs/9244019159):
```bash
Error: 5-31 19:16:55.885][19][error][http] [contrib/golang/filters/http/source/golang_filter.cc:1241] failed to parse golang plugin config: proto: mismatched message type: got "xds.type.v3.TypedStruct", want ""
panic: get config failed, plugin: envoy-go-ldap-auth, configId: 0

goroutine 17 [running, locked to thread]:
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.getOrCreateHttpFilterFactory({0xc0000003f0, 0x12}, 0x0)
	/go/pkg/mod/github.com/envoyproxy/envoy@v1.26.1/contrib/golang/filters/http/source/go/pkg/http/filtermanager.go:44 +0x168
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.createRequest(0x4e17f91b180)
	/go/pkg/mod/github.com/envoyproxy/envoy@v1.26.1/contrib/golang/filters/http/source/go/pkg/http/shim.go:94 +0xda
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.envoyGoFilterOnHttpHeader(0x7f632d0e2dd8?, 0x1, 0x8, 0xa8)
	/go/pkg/mod/github.com/envoyproxy/envoy@v1.26.1/contrib/golang/filters/http/source/go/pkg/http/shim.go:110 +0x5e
[2023-05-31 19:16:55.887][19][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x6500000001
[2023-05-31 19:16:55.887][19][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2023-05-31 19:16:55.887][19][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 7e6031d2a16210660b0[153](https://github.com/Makonike/envoy-go-ldap-auth/actions/runs/5136806180/jobs/9244019321#step:7:154)1b54bc2dc14b1b6e61/1.27.0-dev/Clean/RELEASE/BoringSSL
[2023-05-31 19:16:55.888][19][critical][backtrace] [./source/server/backtrace.h:96] #0: __restore_rt [0x7f6331c8b420]
[2023-05-31 19:16:55.888][19][critical][backtrace] [./source/server/backtrace.h:96] #1: runtime.fatalpanic [0x7f632d11280d]
[2023-05-31 19:16:55.889][19][critical][backtrace] [./source/server/backtrace.h:96] #2: runtime.gopanic [0x7f632d111eda]
[2023-05-31 19:16:55.890][19][critical][backtrace] [./source/server/backtrace.h:96] #3: github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.getOrCreateHttpFilterFactory [0x7f632d4f5168]
[2023-05-31 19:16:55.890][19][critical][backtrace] [./source/server/backtrace.h:96] #4: github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.createRequest [0x7f632d4fb87a]
[2023-05-31 19:16:55.891][19][critical][backtrace] [./source/server/backtrace.h:96] #5: github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.envoyGoFilterOnHttpHeader [0x7f632d4fba1e]
[2023-05-31 19:16:55.892][19][critical][backtrace] [./source/server/backtrace.h:96] #6: _cgoexp_abf5d86fd2bb_envoyGoFilterOnHttpHeader [0x7f632d4fc4d0]
[2023-05-31 19:16:55.892][19][critical][backtrace] [./source/server/backtrace.h:96] #7: runtime.cgocallbackg1 [0x7f632d0e07e2]
[2023-05-31 19:16:55.893][19][critical][backtrace] [./source/server/backtrace.h:96] #8: runtime.cgocallbackg [0x7f632d0e0469]
[2023-05-31 19:16:55.894][19][critical][backtrace] [./source/server/backtrace.h:96] #9: runtime.cgocallbackg.abi0 [0x7f632d144591]
[2023-05-31 19:16:55.894][19][critical][backtrace] [./source/server/backtrace.h:96] #10: runtime.cgocallback.abi0 [0x7f632d141ff3]
ActiveStream 0x4e17f8b1100, stream_id_: 12309474028638519693&filter_manager_: 
  FilterManager 0x4e17f8b11a8, state_.has_1xx_headers_: 0
  filter_manager_callbacks_.requestHeaders(): 
    ':authority', 'localhost:10000'
    ':path', '/'
    ':method', 'GET'
    ':scheme', 'http'
    'user-agent', 'Go-http-client/1.1'
    'accept-encoding', 'gzip'
    'x-forwarded-proto', 'http'
    'x-request-id', '1f2cfe63-edce-49af-9056-eac15c4af7a7'
  filter_manager_callbacks_.requestTrailers():   null
  filter_manager_callbacks_.responseHeaders():   null
  filter_manager_callbacks_.responseTrailers():   null
  &streamInfo(): 
    StreamInfoImpl 0x4e17f8b12d8, protocol_: 1, response_code_: null, response_code_details_: null, attempt_count_: null, health_check_request_: 0, route_name_:     upstream_info_:     null
    OverridableRemoteConnectionInfoSetterStreamInfo 0x4e17f8b12d8, remoteAddress(): [172](https://github.com/Makonike/envoy-go-ldap-auth/actions/runs/5136806180/jobs/9244019321#step:7:173).17.0.1:53446, directRemoteAddress(): 172.17.0.1:53446, localAddress(): 172.17.0.2:10000
Http1::ConnectionImpl 0x4e17f2f7708, dispatching_: 1, dispatching_slice_already_drained_: 0, reset_stream_called_: 0, handling_upgrade_: 0, deferred_end_stream_headers_: 1, processing_trailers_: 0, buffered_body_.length(): 0, header_parsing_state_: Done, current_header_field_: , current_header_value_: 
active_request_: 
, request_url_: null, response_encoder_.local_end_stream_: 0
absl::get<RequestHeaderMapPtr>(headers_or_trailers_): null
current_dispatching_buffer_ front_slice length: 96 contents: "GET / HTTP/1.1\r\nHost: localhost:10000\r\nUser-Agent: Go-http-client/1.1\r\nAccept-Encoding: gzip\r\n\r\n"
ConnectionImpl 0x4e17f81b380, connecting_: 0, bind_error_: 0, state(): Open, read_buffer_limit_: 1048576
socket_: 
  ListenSocketImpl 0x4e17f85cd80, transport_protocol_: raw_buffer

```

**Comment by Makonike** [comment]
By changing the version of the image used for execution to `contrib-v1.26.1`, the issue was resolved.
